title: STARFRAME3D
description: Docs, Article Sources and Resources
theme: just-the-docs

url: https://starframe.github.io/

logo: "/Resources/StarframeLogo.png"
favicon_ico: "Resources/StarframeLogo_Favicon.ico"
color_scheme: starframe



# Enable or disable the side/mobile menu globally
nav_enabled: true
# Heading anchor links appear on hover over h1-h6 tags in page content allowing users to deep link to a particular heading on a page.
heading_anchors: true
# Color scheme supports "light" (default) and "dark"


aux_links:
  LinkedIn: https://www.linkedin.com/in/anita-hackstuhl/

# External navigation links
nav_external_links:
  - title: LinkedIn
    url: https://www.linkedin.com/in/anita-hackstuhl/
    hide_icon: false # set to true to hide the external link icon - defaults to false
  - title: ArtStation
    url: https://www.artstation.com/starframe
    hide_icon: false # set to true to hide the external link icon - defaults to false

# Makes links open in a new tab.
aux_links_new_tab: true
nav_external_links_new_tab: true

back_to_top: true
back_to_top_text: "Back to top"

callouts:
  warning:
    title: Warning
    color: red
  info:
    title: Info
    color: yellow
  note:
    title: note
    color: purple
