title: STARFRAME3D
description: Docs, Article Sources and Resources
theme: just-the-docs

url: https://starframe.github.io/

#logo: "/Resources/StarframeLogo.png"
favicon_ico: "Resources/StarframeLogo_Favicon.ico"
color_scheme: starframe



# Enable or disable the side/mobile menu globally
nav_enabled: true
# Heading anchor links appear on hover over h1-h6 tags in page content allowing users to deep link to a particular heading on a page.
heading_anchors: true
# Color scheme supports "light" (default) and "dark"


aux_links:
  LinkedIn: https://www.linkedin.com/in/anita-hackstuhl/
# Makes Aux links open in a new tab.
aux_links_new_tab: true

callouts:
  warning:
    title: Warning
    color: red
  info:
    title: Info
    color: yellow
